upgrade to returns 14
thomasborgen/storage-bucket pull request #37
Opened 2020-07-08 13:42 UTC by thomasborgen

closes: #34 

semver will be major since this is breaking.

2020-07-08 13:53 UTC, thomasborgen commented
I think we should start a changelog.md now and add it before we merge.
And this merge will mark version 1.0.0, but only because it breaks backwards compatibility and not that its a "milestone"

2020-07-09 04:51 UTC, ChameleonTartu commented on storage_bucket/get.py
> +        storage_bucket_name: str,
@thomasborgen Shouldn't `**kwargs` be passed here as well and down to the `get_bucket`?

2020-07-09 04:54 UTC, ChameleonTartu commented on storage_bucket/delete_file.py
>          timeout: Optional[TIMEOUT_TYPE] = None,
Shouldn't it be `**kwargs`?

2020-07-09 04:55 UTC, ChameleonTartu commented on storage_bucket/delete_file.py
>          timeout: Optional[TIMEOUT_TYPE] = None,
I guess that `TIMEOUT_TYPE ` can be removed from the codebase, now. What do you think?

2020-07-09 04:55 UTC, ChameleonTartu requested changes
@thomasborgen There are a couple of minor comments.

2020-07-16 17:55 UTC, merged